apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: audio
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/atta:2c68be9cd2682c024bea982b5842ec8279a1949d@sha256:af9cc8c9fd921a673ddc9b3b41fb770b1a919f0f03c373babf17c85428d1742a # use pre-built to bootstrap 
          name: app-inference
